<a href="https://colab.research.google.com/github/do2149/Wine-quality-indentification/blob/main/Plotly.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/My Drive/paper')
!pwd

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/My Drive/paper


In [ ]:
import pandas as pd
from numpy import *;#导入numpy的库函数
import numpy as np; #这个方式使用numpy的函数时，需要以np.开头。
import statsmodels.api as sm
import matplotlib.pyplot as plt
%matplotlib inline

df = pd.read_csv("data.csv")
#feature = pd.read_excel("features.xlsx")
label = pd.read_excel("label.xlsx")
#feature.head()
#label.head()
df.head()

quality  fixed acidity  volatile acidity  ...    pH  sulphates  alcohol
0        3           11.6             0.580  ...  3.25       0.57      9.0
1        3           10.4             0.610  ...  3.16       0.63      8.4
2        3            7.4             1.185  ...  3.63       0.54     10.7
3        3           10.4             0.440  ...  3.38       0.86      9.9
4        3            8.3             1.020  ...  3.48       0.49     11.0

[5 rows x 12 columns]

In [ ]:
#df = pd.read_csv('winequality-red1.csv')
#df

# 1. Pre-processing

## Normalization

In [ ]:
from sklearn.preprocessing import StandardScaler

features = ['fixed acidity',
            'volatile acidity',
            'citric acid',
            'residual sugar',
            'chlorides',
            'free sulfur dioxide',
            'total sulfur dioxide',
            'density',
            'pH',
            'sulphates',
            'alcohol']
#separate label
x = df.loc[:,features].values
#separate target
target = df.loc[:,['quality']].values
y = [x for y in target for x in y]
#normolize label
xx = StandardScaler().fit_transform(x)

In [ ]:
x

array([[11.6  ,  0.58 ,  0.66 , ...,  3.25 ,  0.57 ,  9.   ],
       [10.4  ,  0.61 ,  0.49 , ...,  3.16 ,  0.63 ,  8.4  ],
       [ 7.4  ,  1.185,  0.   , ...,  3.63 ,  0.54 , 10.7  ],
       ...,
       [ 7.2  ,  0.33 ,  0.33 , ...,  3.23 ,  1.1  , 10.   ],
       [ 7.2  ,  0.38 ,  0.31 , ...,  3.23 ,  0.76 , 11.3  ],
       [ 7.4  ,  0.36 ,  0.3  , ...,  3.24 ,  0.7  , 11.4  ]])

In [ ]:
xx

array([[ 1.88466826,  0.29149948,  1.99765822, ..., -0.39596939,
        -0.52019345, -1.3357151 ],
       [ 1.19523172,  0.45909378,  1.12470036, ..., -0.97910442,
        -0.16611498, -1.8989186 ],
       [-0.52835961,  3.67131781, -1.39147228, ...,  2.06615629,
        -0.69723268,  0.26002813],
       ...,
       [-0.6432657 , -1.10511966,  0.30309297, ..., -0.52555495,
         2.60749963, -0.39704261],
       [-0.6432657 , -0.82579583,  0.20039205, ..., -0.52555495,
         0.60105502,  0.82323162],
       [-0.52835961, -0.93752536,  0.14904159, ..., -0.46076217,
         0.24697655,  0.91709887]])

In [ ]:
X = df.loc[:,features].values
X

array([[11.6  ,  0.58 ,  0.66 , ...,  3.25 ,  0.57 ,  9.   ],
       [10.4  ,  0.61 ,  0.49 , ...,  3.16 ,  0.63 ,  8.4  ],
       [ 7.4  ,  1.185,  0.   , ...,  3.63 ,  0.54 , 10.7  ],
       ...,
       [ 7.2  ,  0.33 ,  0.33 , ...,  3.23 ,  1.1  , 10.   ],
       [ 7.2  ,  0.38 ,  0.31 , ...,  3.23 ,  0.76 , 11.3  ],
       [ 7.4  ,  0.36 ,  0.3  , ...,  3.24 ,  0.7  , 11.4  ]])

## Visualize all the original dimensions

In [ ]:
import plotly
import plotly.graph_objs as go 
import plotly.express as px

fig = px.scatter_matrix(
    df,
    dimensions=features,
    color='quality'
)
fig.update_traces(diagonal_visible=False)
fig.show()

## Visualize all the principal components

In [ ]:
from sklearn.decomposition import PCA

pca = PCA()
components = pca.fit_transform(df[features])
labels = {
    str(i): f"PC {i+1} ({var:.1f}%)"
    for i, var in enumerate(pca.explained_variance_ratio_ * 100)
}

fig = px.scatter_matrix(
    components,
    labels=labels,
    dimensions=range(5),
    color=df['quality']
)
fig.update_traces(diagonal_visible=False)
fig.show()

## Visualize a subset of the principal components

In [ ]:
from sklearn.datasets import load_boston

n_components = 3

pca = PCA(n_components=n_components)
components = pca.fit_transform(df)

total_var = pca.explained_variance_ratio_.sum() * 100

labels = {str(i): f"PC {i+1}" for i in range(n_components)}
labels['quality'] = 'Median Price'

fig = px.scatter_matrix(
    components,
    color=df['quality'],
    dimensions=range(n_components),
    labels=labels,
    title=f'Total Explained Variance: {total_var:.2f}%',
)
fig.update_traces(diagonal_visible=False)
fig.show()

## Visualize PCA with `px.scatter_3d`

In [ ]:
pca = PCA(n_components=7)
components = pca.fit_transform(x)

total_var = pca.explained_variance_ratio_.sum() * 100

fig = px.scatter_3d(
    components, x=0, y=1, z=2, color=df['quality'],
    title=f'Total Explained Variance: {total_var:.2f}%',
    labels={'0': 'PC 1', '1': 'PC 2', '2': 'PC 3'}
)
fig.show()

In [ ]:
x

array([[11.6  ,  0.58 ,  0.66 , ...,  3.25 ,  0.57 ,  9.   ],
       [10.4  ,  0.61 ,  0.49 , ...,  3.16 ,  0.63 ,  8.4  ],
       [ 7.4  ,  1.185,  0.   , ...,  3.63 ,  0.54 , 10.7  ],
       ...,
       [ 7.2  ,  0.33 ,  0.33 , ...,  3.23 ,  1.1  , 10.   ],
       [ 7.2  ,  0.38 ,  0.31 , ...,  3.23 ,  0.76 , 11.3  ],
       [ 7.4  ,  0.36 ,  0.3  , ...,  3.24 ,  0.7  , 11.4  ]])

In [ ]:
from sklearn.decomposition import KernelPCA

kpca = KernelPCA(gamma= 0.05, kernel="rbf", n_components=7)
principalComponents2 = kpca.fit_transform(x)
principalDf2 = pd.DataFrame(data = principalComponents2,
                            columns = ['principal component 1',
                                      'principal component 2', 
                                      'principal component 3', 
                                      'principal component 4',
                                      'principal component 5',
                                      'principal component 6',
                                      'principal component 7'])
principalDf2

principal component 1  ...  principal component 7
0                 -0.084717  ...              -0.087250
1                  0.452251  ...               0.104507
2                  0.593484  ...              -0.133106
3                 -0.070011  ...               0.010378
4                  0.582447  ...               0.032600
...                     ...  ...                    ...
1594               0.678017  ...              -0.031895
1595              -0.065415  ...               0.007169
1596               0.539493  ...              -0.011043
1597              -0.266366  ...               0.203070
1598              -0.162830  ...              -0.004870

[1599 rows x 7 columns]

In [ ]:
finalDf2 = pd.concat([principalDf2, df[['quality']]],axis = 1)
finalDf2

principal component 1  ...  quality
0                 -0.084717  ...        3
1                  0.452251  ...        3
2                  0.593484  ...        3
3                 -0.070011  ...        3
4                  0.582447  ...        3
...                     ...  ...      ...
1594               0.678017  ...        8
1595              -0.065415  ...        8
1596               0.539493  ...        8
1597              -0.266366  ...        8
1598              -0.162830  ...        8

[1599 rows x 8 columns]

In [ ]:
total_var = pca.explained_variance_ratio_.sum() * 100

fig = px.scatter_3d(
    principalComponents2, x=0, y=1, z=2, color=finalDf2['quality'],
    title=f'Total Explained Variance: {total_var:.2f}%',
    labels={'0': 'PC 1', '1': 'PC 2', '2': 'PC 3'},
)
fig.show()

## Plotting explained variance

In [ ]:
pca = PCA()
pca.fit(df)
exp_var_cumul = np.cumsum(pca.explained_variance_ratio_)

px.area(
    x=range(1, exp_var_cumul.shape[0] + 1),
    y=exp_var_cumul,
    labels={"x": "# Components", "y": "Explained Variance"}
)

## Visualize Loadings

In [ ]:
from sklearn.preprocessing import StandardScaler

pca = PCA(n_components=2)
components = pca.fit_transform(x)

loadings = pca.components_.T * np.sqrt(pca.explained_variance_)

fig = px.scatter(components, x=0, y=1, color=df['quality'])

for i, feature in enumerate(features):
    fig.add_shape(
        type='line',
        x0=0, y0=0,
        x1=loadings[i, 0],
        y1=loadings[i, 1]
    )
    fig.add_annotation(
        x=loadings[i, 0],
        y=loadings[i, 1],
        ax=0, ay=0,
        xanchor="center",
        yanchor="bottom",
        text=feature,
    )
fig.show()

In [ ]:
x

array([[11.6  ,  0.58 ,  0.66 , ...,  3.25 ,  0.57 ,  9.   ],
       [10.4  ,  0.61 ,  0.49 , ...,  3.16 ,  0.63 ,  8.4  ],
       [ 7.4  ,  1.185,  0.   , ...,  3.63 ,  0.54 , 10.7  ],
       ...,
       [ 7.2  ,  0.33 ,  0.33 , ...,  3.23 ,  1.1  , 10.   ],
       [ 7.2  ,  0.38 ,  0.31 , ...,  3.23 ,  0.76 , 11.3  ],
       [ 7.4  ,  0.36 ,  0.3  , ...,  3.24 ,  0.7  , 11.4  ]])

In [ ]:
from sklearn.preprocessing import StandardScaler

kpca = KernelPCA(gamma= 0.05, kernel="rbf", n_components=7)
components = kpca.fit_transform(x)

loadings = pca.components_.T * np.sqrt(pca.explained_variance_)

fig = px.scatter(components, x=0, y=1, color=df['quality'])

for i, feature in enumerate(features):
    fig.add_shape(
        type='line',
        x0=0, y0=0,
        x1=loadings[i, 0],
        y1=loadings[i, 1]
    )
    fig.add_annotation(
        x=loadings[i, 0],
        y=loadings[i, 1],
        ax=0, ay=0,
        xanchor="center",
        yanchor="bottom",
        text=feature,
    )
fig.show()
loadings

array([[-2.06492993e-01, -1.81911784e-01],
       [ 1.29457440e-02, -1.52966406e-02],
       [ 5.75464105e-03, -2.30995356e-02],
       [ 2.91227774e-01,  8.47532995e-02],
       [ 2.14594441e-03, -1.80130507e-03],
       [ 7.36937886e+00,  7.42326768e+00],
       [ 3.28530926e+01, -1.66629242e+00],
       [ 1.25427902e-04, -1.90287152e-04],
       [-9.02440011e-03,  2.49035756e-02],
       [ 7.52172121e-03,  4.71097505e-03],
       [-2.14102638e-01,  1.10856209e-01]])

# 2. KNN

In [ ]:
from sklearn import neighbors, datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report

In [ ]:
features = ['principal component 1',
            'principal component 2', 
            'principal component 3', 
            'principal component 4',
            'principal component 5',
            'principal component 6',
            'principal component 7']
#分离出特征
xx = finalDf2.loc[:,features].values
#分离目标
target = finalDf2.loc[:,['quality']].values
yy = [x for y in target for x in y]

x_train, x_test, y_train, y_test = train_test_split(xx, yy, test_size=0.2, random_state=45, stratify=y)

In [ ]:
xx

array([[-0.08471724, -0.07930674, -0.11756987, ...,  0.05605954,
         0.03530565, -0.08724993],
       [ 0.45225114,  0.18345067, -0.13041278, ...,  0.07205181,
         0.24901972,  0.10450673],
       [ 0.59348448, -0.077953  ,  0.09994586, ...,  0.00193875,
         0.03726354, -0.13310646],
       ...,
       [ 0.53949253, -0.2053056 ,  0.19073859, ..., -0.06331274,
        -0.02350669, -0.01104287],
       [-0.26636626, -0.07979361,  0.45095391, ...,  0.28468597,
        -0.07016332,  0.20307027],
       [-0.16282973, -0.00423924,  0.2191006 , ...,  0.4095783 ,
        -0.18011251, -0.00486987]])

In [ ]:
from sklearn.covariance import EmpiricalCovariance, MinCovDet

# fit a Minimum Covariance Determinant (MCD) robust estimator to data
robust_cov = MinCovDet().fit(xx)

# compare estimators learnt from the full data set with true parameters
emp_cov = EmpiricalCovariance().fit(xx)

robust_cov_y = MinCovDet().fit(target)

# compare estimators learnt from the full data set with true parameters
emp_cov_y = EmpiricalCovariance().fit(target)

In [ ]:
knn = KNeighborsClassifier(n_neighbors=11,
                           weights='distance',
                           algorithm='brute',
                           leaf_size=30,
                           metric='mahalanobis',
                           metric_params={'V': emp_cov},
                           n_jobs=1)

In [ ]:
#定义一个knn分类器对象
knn.fit(x_train, y_train)

y_predict = knn.predict(x_test) 
#调用该对象的测试方法，主要接收一个参数：测试数据集
probility = knn.predict_proba(x_test)
#计算各测试样本基于概率的预测
neighborpoint = knn.kneighbors(x_test[-1:], 25, False)
#计算与最后一个测试样本距离在最近的5个点，返回的是这些样本的序号组成的数组
score = knn.score(x_test,y_test,sample_weight=None)
accuracy = accuracy_score(y_test, y_predict)
precision = precision_score(y_test, y_predict, average='weighted')
recall = recall_score(y_test, y_predict, average='weighted')
#调用该对象的打分方法，计算出准确率

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [ ]:
print('y_predict = ')  
print(y_predict)  
#输出测试的结果
 
print('y_test = ')
print(y_test)    
#输出原始测试数据集的正确标签，以方便对比
print ('Accuracy:',accuracy)
print ('Precision:',precision)
print ('Recall:',recall)
#输出准确率计算结果
print ('neighborpoint of last test sample:',neighborpoint)
 
print ('probility:',probility)

y_predict = 
[5 6 6 6 6 6 7 6 6 5 5 5 7 6 6 6 5 5 6 6 5 6 6 5 5 6 5 5 6 6 7 5 5 5 6 5 5
 5 5 5 5 5 7 5 5 6 6 7 5 5 6 5 6 6 5 5 5 6 6 6 5 5 6 5 5 5 6 6 6 5 7 5 5 6
 6 5 6 5 5 6 5 6 6 7 5 5 5 6 7 5 6 5 5 6 5 5 6 5 7 5 5 5 5 6 5 5 5 5 5 5 5
 5 5 6 5 5 6 5 6 6 6 6 5 5 6 5 4 6 7 5 5 5 6 5 7 6 5 6 6 7 6 6 6 7 6 5 5 5
 5 6 6 5 5 7 6 6 7 6 6 6 6 6 6 5 5 7 6 6 6 6 5 5 5 6 6 6 5 5 6 5 5 5 5 5 6
 5 6 5 5 6 6 5 5 5 5 7 5 5 6 6 5 6 5 7 6 6 5 5 5 5 5 5 7 7 5 5 5 7 7 5 6 6
 6 5 5 6 5 5 6 6 6 6 6 5 6 5 5 6 5 6 6 5 7 5 7 6 5 7 5 5 5 5 5 7 7 7 5 7 5
 5 5 5 6 6 6 5 6 7 6 5 7 5 6 5 5 7 5 6 7 6 5 5 6 7 6 6 5 5 5 6 6 5 5 6 6 7
 6 6 6 6 6 5 6 5 6 5 7 5 6 5 5 5 6 5 5 6 5 6 5 6]
y_test = 
[6, 5, 6, 4, 6, 6, 7, 5, 6, 5, 5, 7, 6, 6, 7, 6, 5, 7, 6, 5, 5, 8, 6, 5, 6, 8, 6, 6, 7, 7, 7, 6, 5, 6, 4, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 6, 6, 7, 6, 5, 6, 5, 5, 5, 5, 7, 5, 6, 5, 6, 6, 5, 6, 5, 5, 5, 5, 6, 6, 5, 5, 5, 5, 6, 8, 5, 5, 5, 5, 6, 6, 5, 5, 7, 6, 6, 5, 5, 7, 5, 6, 5, 5, 6, 5, 5, 5, 6, 7, 7, 5, 5, 5, 6, 6, 6, 5, 7, 5,

In [ ]:
ans = classification_report(y_test, y_predict, digits=5)
print(ans)

              precision    recall  f1-score   support

           3    0.00000   0.00000   0.00000         2
           4    0.00000   0.00000   0.00000        11
           5    0.63924   0.74265   0.68707       136
           6    0.64000   0.62500   0.63241       128
           7    0.61111   0.55000   0.57895        40
           8    0.00000   0.00000   0.00000         3

    accuracy                        0.63438       320
   macro avg    0.31506   0.31961   0.31641       320
weighted avg    0.60407   0.63438   0.61734       320



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

